### ISSUE TITLE
Kerbal EVA Antennas should use much less electricity

### ISSUE THREAD

**Issue by mwerle** [toadicus/AntennaRange#1]
The Kerbal EVA Antenna feature relies on EVA Manager, which in turn pulls/returns resources from the pod.  Requiring 100 electric charge is prohibitive early in the game (as well as buggy - see bug report in EVA Manager).

Given that the idea is to have a VERY short range antenna, using 10 EC and tweaking the kerbal antenna module suitably makes more sense (IMHO).

Otherwise you end up with an unbalanced situation:

Either Kerbals contribute significantly to the energy budge of a ship if they come with fully-loaded batteries in the early game
or 
Kerbals drain their pods of electricity when they go on EVA, leaving the pod unable to act as relay (or for multi-Kerbal pods, out of control)

**Comment by mwerle** [comment]
Potential fix (still allows for 2 EVA reports to be sent to the ship so doesn't change the usability of the mod)

```
diff --git a/GameData/AntennaRange/AntennaRange.cfg b/GameData/AntennaRange/AntennaRange.cfg
index 8515193..8909f98 100644
--- a/GameData/AntennaRange/AntennaRange.cfg
+++ b/GameData/AntennaRange/AntennaRange.cfg
@@ -122,7 +122,7 @@ EVA_MODULE

        packetInterval = 0.2
        packetSize = 1
-       packetResourceCost = 6.25
+       packetResourceCost = 0.625

        requiredResource = ElectricCharge
 }
@@ -130,8 +130,8 @@ EVA_MODULE
 EVA_RESOURCE
 {
        name = ElectricCharge
-       amount = 100
-       maxAmount = 100
+       amount = 0
+       maxAmount = 10
 }
```

**Comment by toadicus** [comment]
One of the reasons for going with 100 as the default implementation is "accidental" compatibility with TACLS, which gives Kerbals 90-something ElectricCharge and which I cannot prevent from doing so.  But, we could isolate TACLS-adjacent behavior and do something like this for the default implementation.  I don't particularly disagree with the idea, with one big caveat:

Because I do not model ElectricCharge use "down the chain", making the EVA antenna drastically more efficient than the other antennas effectively encourages players to take all of their data out on an EVA to transmit it for essentially free.

**Comment by mwerle** [comment]
Ah, I thought it did model electric charge use along the chain; I'm marginally sure in an older savegame I couldn't transmit anymore because one of my relay sats had accidentally run out of power. I may well be wrong! :)

In that case yes, reducing the power use of the Kerbal Antenna does lead to an exploit. Although the exploit is not all that bad,as well as inconvenient since only 16 Mits (2 EVA reports) can be transmitted with one fully charged Kerbal.

It was just an idea to try to balance the early game a bit, but it doesn't really take that long to get battery tech.
