### ISSUE TITLE
Transmitting on EVA: ArgumentOutOfRangeException: Argument is out of range

### ISSUE THREAD

**Issue by jberkman** [toadicus/AntennaRange#4]
KSP 1.1 w/ AR preview:

```
[LOG 15:57:38.677] Sending data to vessel comms. 1 devices to choose from. Will try to pick the best one
[EXC 15:57:38.679] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
    System.Collections.Generic.List`1[IScalarModule].get_Item (Int32 index)
    ModuleDataTransmitter.GetFxModuleScalar (System.Collections.Generic.List`1 modules)
    ModuleDataTransmitter+<transmitQueuedData>c__Iterator68.MoveNext ()
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    ModuleDataTransmitter:TransmitData(List`1)
    AntennaRange.ModuleLimitedDataTransmitter:TransmitData(List`1)
    ModuleScienceExperiment:sendDataToComms(ScienceData)
    KSP.UI.Screens.Flight.Dialogs.ExperimentsResultDialog:onBtnTransmit()
    UnityEngine.EventSystems.EventSystem:Update()
```

[KSP.log.txt](https://github.com/toadicus/AntennaRange/files/211334/KSP.log.txt)

**Comment by toadicus** [comment]
You have a bunch of other mods that are also causing problems: ModuleAnimateEmissive,  EVE, and KerbalAlarmClock.  That's not necessarily related, but since the problem you're observing is not happening directly in my code (Squad's code is failing to properly list some modules when my code calls it), we need to rule out the possibility.  Can you duplicate this problem without any other mods (except ModuleManager) installed?  If not, when adding which mod does the problem recur?

Also need reproduction steps.

**Comment by jberkman** [comment]
Sorry, reproduction steps were so simple I left them out!
1. launch Mk1 command pod
2. EVA and jump off ladder
3. perform EVA report
4. transmit data

repeat steps 3 and 4, report never gets sent. note error in debug log.

cheers!

[KSP.log.txt](https://github.com/toadicus/AntennaRange/files/211533/KSP.log.txt)

**Comment by jberkman** [comment]
Also happens when I try to transmit data on a different experiment, so it's not just the EVA.

**Comment by toadicus** [comment]
I was able to reproduce when transmitting from an EVA, but not from a probe.  Looks like Squad's code might be looking for an animation, which isn't there.  I'll look for a way around.  Thanks!

**Comment by jberkman** [comment]
I think that was still a crewed flight, I just wasn't on EVA.

**Comment by toadicus** [comment]
I am able to transmit from pods using stock antennas just fine; if you are having trouble with that as well I'll need new information on how to duplicate.  Also, that's probably a separate issue given the below.

The bug that I found will only happen on antennas that do not have animations assigned, and is actually a Squad bug.  Since we're still in open beta I've filed a bug on their end and hope to see a fix rather than me developing an ugly workaround.

**Comment by jberkman** [comment]
That's consistent with what I was doing, I was using the nosecone from SoundingRockets which I added AntennaRange support to (that's how it works with RT). It doesn't have an animation either.

I didn't see the bug on their tracker; do you have the number handy? Thanks!

**Comment by toadicus** [comment]
It's not in any of the public trackers, so you'd only be able to see it if you have more access than the average bear.  If so, it's 8808.

**Comment by toadicus** [comment]
This ought to be fixed as of KSP b1208.  Unfortunately, the store page isn't downloading the latest Experiments version for me, so I can't check just yet.

**Comment by jberkman** [comment]
Yeah, WFM in build 1209. thanks!
